language: node_js
node_js:
- '8'
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run build
deploy:
- provider: script
  script: deploy-build
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: mh4tdXUoNzlMmF+ItMLsXlTpVbDDKLhgJWQEJYtJ4kX2b3l60l88r2Wqn84gDW6zBwE1+FiudVbeh9mJGyxnG7YbxPpyQv5mElFH+6SzeJ8R99/0LjDcDfUt85H+N/ST/4zgcE6gMpddo3wZgKuEQmvDuc5+3Ydyr+NzjAN7+22vkLmQ6eq2JTDBJBAXm3SZ3K2Uh2+2XmXibhgzpN+I3EpgF4JmOBn8+xCIVC9U6t3sVBoUDQEgdCWKpd/kJ10XYPReqFZC482W56k/JhzI06rBmjyuHLbuWPTdVhcDUULPt7bWEMdlOGmf2OTTGEXEmNjd5PwvMAk0WIWzUmGnv5ZxKW1fP/4BVStmiogyLWuOLTxXmWbmHm9Uh4TvEbBKWeWqS8y3Om19fDBV47ePjY8jkNcHF2I++suYah0TDdawwStIxbZ93GjSC9WujWF1byU5Jk5vzLPI/G3vu3zMafOaWQ5G73Tvgg8aUJEgs20phexL5uuqYO4CEwXQFriWlrdV5UsMw3V3AZb+yiY4cwsCpI8QkMvNUG5X04nAiRUHRE0ugZfw9/HicTXcwg/bzv15ZTOJNcicH4C57lBHhJpamYE3mjU0dhsCmRdvhjukxiFGaYFwGkpTSOvu6UYhHhtX4Drtol3RMh6viXodtw/DhdqGLUh8n/4YV/2teQg=
    on_success: change
    on_failure: always
env:
  global:
    secure: T+nCVehFCSS+dsujv9Q+Cx6CTS8fH8XjfwQsrO4pvt34LwAV465Dy3RySk1N6YXrR26hXebnExtFrxYulrP80cv1ST3ydhOLpWcj4aTh5p8/MMFXBYeuURelgloHPIz7hLhcePoD6LAwC96TuaWCoZNBEDRjujdS7mcyH6miW+dmOuziE8GDEpL199CDKOYhqtdFSGboiAvRU2fL9K4A2moDGi1qTxBG6iXhaQgnbVw6AqU1g0vV16+iarCHC391O63i+19RHQ5UWk3ei0WkW9af5GfGwT8a7Bm6oRa6FRgBf8FZ6CJmbWlNrBrBGsdKDghh1OXmU40eXkzI9O74JUlDtrKspWzLeXXNXIbyVELZMDDcbxkXEpzQ+TVwz5JfOkthnpO4PXzU8xmRf+WLyeLXq9lMlrMEGmuzjjuR9XSYQTBfOk1xfi0/S2ymGt3Z5EMG9y8bCBxg22vcanjcWeIQ2EutVI92zgOfSGBUgmfMuzgSQRnj8/ktdAADJQOur/QJvysg0ybA2i3fw7fK94t5lu6eo7kkVUIVbJj4xeq6ITtX++DWdRB0EbmWrm/Nw4VQ1ZEjj09hGQr4bcqq+XEiIkl/YwDtml6tLeNQwFegd+Yx2Q1I3QYNQrwurLQThi0qRY+KGJNjPfIboNRyE/MDl8B0/Cdl7GIjTPDTN98=
