language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
env:
  global:
  - secure: KEFsjK1SyvtDFbrWKJ1S0oJCrqBzEUHUMAsguLo9GgiYfyFE8AJY0HSX36Ln6HhgDT91au9o8t6zK+pk27JcqIXPXruQXth+ZRGZayP+mFqVPPT1Qd/qf82CSkgsnGIpnpNxT72MgTqUxUF/ux/uUxflzv9myLLJw4ZGhiD7MBfBAN2rMC9MAty9HR5exF2jiFSBSKQP6XADhqaRfnIqhFdYUGTLzVOSGUDKEcHtPskOiOAc3O75IS+fHROiMn5SJ9GuYJagLHpwIvLbF4QHs2Y7yxEqniOe4dmjmjLYbncALrt+wZBZK7FfWzqDG3vqWHAyGlsGKpkl/MJNB+yT6jPGtBomb/cmF+GM1/fGikBVllxiHDUPBp9dm3pgxtMmL57GFQ9oqgXQpz9qLR/QqWWqKn9fwKR4B7uw2EzszounExLBKio/UZCmaOBYysM18nkLO/52L7n/mfUxc5yJihumqx5KE783PC8JLSN2kdAeqVJLEPURMZq4JZ3aBOlFLc7z8bkZ0sfUkZiTkLCeInLHXmICTrgFdB3qu4GC3WYAzJO8x7h0RdhZYvr4xDOxrbUqgdPFYCw1ou84MlVaHkXGvj94I8R1yvSwPFRZDgyCKdMhPbfjBMlqDajjxk5mrRAW76WvnT3Ssooz8sY4PmjQ1qEqiFIErKEeC9aVYzk=
  - secure: HQzzHHclaJK5xyGQkel92X7nAE9sWLiPrYWz2DGHYsmopkUbuoTGyrF2GEhbox6Fn9ug3WVM1Wts+dX1y3zM/hVI92tbWpLo75EzZHdiKPYFLuNGoOLY1jqiWD6AyCcxycSDIh16sXVo8S2jQThejaMKu1DMXSfMpP9J6Az94m45bz08+Dk7cRyLjVaTrOB7/R+7ywAisl5UdbvuH7k+oBKxfbEj6GVB+kcit2Dx6SxKaOd1wqSIJyjtxi7UxJnXHjfdUZCUdPS9G63nTBW+wNMTbvCarKJYEPJUq/gk/RYzuf/LJ8HJvhCfHsuM8sfvOoPsjC8ZthqxDQCaMgh/Yt5BvOdYmH6RDtDidLCz7lV7/CSw+6hKBy206BecAQscpm37lIRiRt67CxAhrDeGMIXTekGIt3bMoiNuSVs7LE0YVG1pZM9ZkJKT+ALzNhk1b7dnbgkMQ4k7hYSj/fH/+7Psp/ddtY98E9V3NsuA8KN+yRfDcJ/a1pYlaJ2CxpQojl8PAn+i79Qx4X9Jh2G/S178p3eIYiLiVUgCFBhD3HVDHdmpK+4EjTuoSCMyGThq2jjtr1IHJ04C+9tmfAxBLU+zq1XTzG30PNmbYGll3VGCEUthVCRacDa0x1e9cvmzAtdweYU4D+5+CiltyjfiGqKsGxm39oCU4DuTB3CytqY=
